language: python

python:
    - 3.6
    - 2.7

env:
    matrix:
        - NUMPY_VERSION=1.12


before_install:
    - if [ $TRAVIS_BRANCH == coverity_scan -a ${TRAVIS_JOB_NUMBER##*.} != 1 ]; then exit 0; fi
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython
    - conda install --yes -c bccp runtests
    - python setup.py install

script:
    - if [ $TRAVIS_BRANCH == coverity_scan ]; then exit 0; fi
    - python ./run-tests.py
    - bash check_tag.sh gaepsi2/version.py

deploy:
    - provider: pypi
      distributions: sdist
      server: https://pypi.python.org/pypi
      user: "rainwoodman"
      password:
          secure: "ZiLLantQMOb2JDNknVaM6LZiYfz4jipHArefbWZy1QyTXwS39fh4sXQEeeAZkcSWJuzm0zGybdlN8ooSAHuwA94tK5K3jlG9qhKQsSm2Nix/tiJA/qcn1WrGJ3VhBFEpxoLPpUCcyvmjTd/K7kJrBQm+UfeUwrID/OhLKNii+B8Y2gNok8PnzOeemDxSqXF87t91UHAWYIeIuUeqRtOa6A/UXtzVgahfnK8f4pWkZKUlRrLaZaZYtFgLzRVXIGB78Kv/wKUxCapWBw8bvB/pBTH+d6PDOxgIeMPmYcnAaWy1yBuoSNU3gcRVhXNY1N5cMlQMSLg3I9Imail2S3s/WQ/AXFy56AXAQ+GKYoKymhHP2CFubpV0BGzDT+XkI62hUJSj/TMygTvxHnNJHKCfJ42Agv5va/WnRUB4P4OIo2txlFmNKTtrNsHB8UAblDeqYBxSLJtJZ7yPczyZ57s0eJ5dGicVKyRROtJVzaMQLqsY82abYqpr4M2rIc+RpZib2vFGlPXzX8hInHj5yBG21kQnLrApYnbjESaGVyji1h65u0bObg91xu5FItiUmVHwkvNGI8vtHqBn9IoXVJExQ6WA35QLzFqLyaHeOFAf7vELA95e84w87Ni4J92Ahuh8vuO0y55GYl1Yc3CAluip4+Lie1TefAY6iLipYzHhmog="


      on:
        tags   : true
        condition : ${TRAVIS_JOB_NUMBER##*.} == 1
